Train:
  batch_size: 64
  learning_rate: 0.1
  reg: 0.0005
  epochs: 10
  steps: [6, 8]
  warmup: 0
  momentum: 0.9

network:
  model: ResNet-32 # TwoLayerNet or VanillaCNN or MyModel or ResNet-32
  save_best: True

data:
  imbalance: imbalance # regular or imbalance
  reweight: True
  beta: 0.9999

loss:
  loss_type: Focal # CE or Focal
